name: Generate and Deploy Typedoc

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.1

    - name: Install dependencies
      run: npm ci

    - name: Generate TypeDoc
      run: npm install -g typedoc && typedoc --out docs/ src/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs