name: Release

on:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: write

jobs:
  deploy_npm_package_and_typedoc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.21.0
        registry-url: 'https://registry.npmjs.org'

    - name: Update npm to 11.6.2
      run: npm install -g npm@11.6.2

    - name: Install Dependencies
      run: npm ci

    - name: Publish to npm via OIDC
      run: npm publish

    - name: Generate Typedoc
      run: npm run build:typedoc

    - name: Deploy Typedoc to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs